- name: VPC set-up
  hosts: localhost
  connection:  local
  gather_facts: false
  tasks:
  - name: Import VPC variables
    include_vars: vars/vpc_setups

  - name: create vpc 
    ec2_vpc_net:
       name: "{{vpc_name}}"
       cidr_block: "{{vpc_cidr}}"
       region: "{{region}}"
       tags:
         module: ec2_vpc_net
         this: works
       dns_hostnames: yes
       dns_support: yes
       tenancy: default
       state: "{{state}}"
    register: vpout

  - debug:
     var: vpout


  - name: public subnet-1 creation
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpout.vpc.id}}"
      cidr: "{{pub_subnet_1}}"
      az: "{{zone1}}"
      region: "{{region}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: public-Subnet-1
    register: pubsub1_out


  - name: public subnets-2 creation
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpout.vpc.id}}"
      cidr: "{{pub_subnet_2}}"
      az: "{{zone2}}"
      region: "{{region}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: public-Subnet-2
    register: pubsub1_out

  - name: public subnets-3 creation
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpout.vpc.id}}"
      cidr: "{{pub_subnet_3}}"
      az: "{{zone3}}"
      region: "{{region}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: public-Subnet-3
    register: pubsub1_out
