- name: Build, generate artifact, copy artifactn and sql file to file directory
  hosts:  localhost
  connection : local
  become: yes
  tasks:  
  - name:  intsall jdk and maven
    apt: 
      name: "{{item}}"
      state: present
      update_cache:  yes
    loop:
    - openjdk-8-jdk
    - maven


  - name:  Clone source code from github
    git:
      repo: 'https://github.com/devopshydclub/vprofile-project.git'
      dest: ./Vprofile-repo
      version: vp-rem
    register: git_status

  - name:  Build artifact 
    command: "mvn install"
    args: 
     chdir: Vprofile-repo
    when: git_status.changed
    register: mvn_info

  - name: copy Artifcat to files diretory
    copy: 
      src: "{{item}}"
      dest: files/ROOT.war 
    with_fileglob: Vprofile-repo/target/*.war
 
  - name: copy SQL file to files directory
    copy: 
       src: Vprofile-repo/src/main/resources/db_backup.sql
       dest: files/db_backup.sql

